### ISSUE TITLE
TypeError when running `control/ind_contrib.py`

### ISSUE THREAD

**Issue by DomNelson** [DomNelson/ISGen#2]
Running `python ind_contrib.py -p test_ped.txt -i 10 -o test_out.h5` results in the error:

```
Traceback (most recent call last):
  File "scripts/control/ind_contrib.py", line 181, in <module>
    main(args)
  File "scripts/control/ind_contrib.py", line 153, in main
    hdf5_to_sparse.main(sparse_args)
  File "scripts/control/hdf5_to_sparse.py", line 74, in main
    sp_array = sparse.coo_matrix((data, (rows, cols)))
  File "~/anaconda2/lib/python2.7/site-packages/scipy/sparse/coo.py", line 150, in __init__
    self._shape = check_shape((M, N))
  File "~/anaconda2/lib/python2.7/site-packages/scipy/sparse/sputils.py", line 281, in check_shape
    new_shape = tuple(operator.index(arg) for arg in args)
  File "~/anaconda2/lib/python2.7/site-packages/scipy/sparse/sputils.py", line 281, in <genexpr>
    new_shape = tuple(operator.index(arg) for arg in args)
TypeError: 'numpy.float64' object cannot be interpreted as an index
Closing remaining open files:test_out.h5...done
```

**Comment by DomNelson** [comment]
Version 1.2.0 of `scipy` requires (row, col) of sparse array to be integers. Columns were loaded from hdf5 file as floats
